//
//  UIColor+GLFAdditions.swift
//
//  Generated by Zeplin on 11/9/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

extension UIColor {

    // New Colors //
    @nonobjc class var glfStackBackColor: UIColor {
        return UIColor(red: 249.0/255.0, green: 249.0 / 255.0, blue: 249.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfFairway: UIColor {
        return UIColor(red: 78.0 / 255.0, green: 145.0 / 255.0, blue: 126.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfGreen: UIColor {
        return UIColor(red: 125.0 / 255.0, green: 197.0 / 255.0, blue: 177.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfBunker: UIColor {
        return UIColor(red: 197.0 / 255.0, green: 127.0 / 255.0, blue: 127.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfRough: UIColor {
        return UIColor(red: 64.0 / 255.0, green: 99.0 / 255.0, blue: 89.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfBorder: UIColor {
        return UIColor(red: 239.0/255.0, green: 239.0 / 255.0, blue: 239.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfStrokesNbg: UIColor {
        return UIColor(red: 247.0/255.0, green: 234.0 / 255.0, blue: 234.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfStrokesPbg: UIColor {
        return UIColor(red: 223.0/255.0, green: 237.0 / 255.0, blue: 233.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfStrokesNtc: UIColor {
        return UIColor(red: 255.0/255.0, green: 140.0 / 255.0, blue: 143.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfStrokesPtc: UIColor {
        return UIColor(red: 0/255.0, green: 193.0 / 255.0, blue: 140.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfNegativeClub: UIColor {
        return UIColor(red: 215/255.0, green: 118.0 / 255.0, blue: 129.0 / 255.0, alpha: 1.0)
    }
    //------//
    
    @nonobjc class var glfWhite: UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfWhiteTwo: UIColor {
        return UIColor(white: 248.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfSeafoamBlue: UIColor {
        return UIColor(red: 129.0 / 255.0, green: 195.0 / 255.0, blue: 215.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfBlueyGreen: UIColor {
        return UIColor(red: 46.0 / 255.0, green: 159.0 / 255.0, blue: 128.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfBluegreen50: UIColor {
        return UIColor(red: 0.0, green: 138.0 / 255.0, blue: 100.0 / 255.0, alpha: 0.5)
    }
    
    @nonobjc class var glfFlatBlue75: UIColor {
        return UIColor(red: 58.0 / 255.0, green: 124.0 / 255.0, blue: 165.0 / 255.0, alpha: 0.75)
    }
    
    @nonobjc class var glfGreenBlue: UIColor {
        return UIColor(red: 0.0, green: 204.0 / 255.0, blue: 148.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfGreenishTurquoise: UIColor {
        return UIColor(red: 0.0, green: 253.0 / 255.0, blue: 184.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfOffWhite: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 245.0 / 255.0, blue: 230.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfBlack: UIColor {
        return UIColor(white: 55.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfFlatBlue: UIColor {
        return UIColor(red: 58.0 / 255.0, green: 124.0 / 255.0, blue: 165.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfDarkGreen: UIColor {
        return UIColor(red: 0.0 / 255.0, green: 130.0 / 255.0, blue: 100.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfBluegreen: UIColor {
        return UIColor(red: 0.0, green: 138.0 / 255.0, blue: 100.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfBlack40: UIColor {
        return UIColor(white: 0.0, alpha: 0.4)
    }
    
    @nonobjc class var glfBlack75: UIColor {
        return UIColor(white: 0.0, alpha: 0.75)
    }
    
    @nonobjc class var glfPaleTeal: UIColor {
        return UIColor(red: 127.0 / 255.0, green: 196.0 / 255.0, blue: 177.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfLightBlueGrey: UIColor {
        return UIColor(red: 191.0 / 255.0, green: 226.0 / 255.0, blue: 216.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfRosyPink: UIColor {
        return UIColor(red: 239.0 / 255.0, green: 108.0 / 255.0, blue: 111.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfRosyPink85: UIColor {
        return UIColor(red: 239.0 / 255.0, green: 108.0 / 255.0, blue: 111.0 / 255.0, alpha: 0.85)
    }
    
    @nonobjc class var glfBluegreen75: UIColor {
        return UIColor(red: 0.0, green: 138.0 / 255.0, blue: 100.0 / 255.0, alpha: 0.75)
    }
    
    @nonobjc class var glfDustyRed: UIColor {
        return UIColor(red: 185.0 / 255.0, green: 58.0 / 255.0, blue: 61.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfPaleTealTwo: UIColor {
        return UIColor(red: 140.0 / 255.0, green: 202.0 / 255.0, blue: 185.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfWarmGrey: UIColor {
        return UIColor(white: 151.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfWhiteThree: UIColor {
        return UIColor(white: 246.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfBlack50: UIColor {
        return UIColor(white: 0.0, alpha: 0.5)
    }
    @nonobjc class var glfWhite75: UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 0.75)
    }
    
    @nonobjc class var glfWhiteFour: UIColor {
        return UIColor(red: 248.0 / 255.0, green: 248.0 / 255.0, blue: 247.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfBlack5: UIColor {
        return UIColor(white: 0.0, alpha: 0.05)
    }
    
    @nonobjc class var glfBluegreen25: UIColor {
        return UIColor(red: 0.0, green: 138.0 / 255.0, blue: 100.0 / 255.0, alpha: 0.25)
    }
    
    @nonobjc class var glfLightGreyBlue: UIColor {
        return UIColor(red: 156.0 / 255.0, green: 189.0 / 255.0, blue: 210.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var glfRosyPink50: UIColor {
        return UIColor(red: 239.0 / 255.0, green: 108.0 / 255.0, blue: 111.0 / 255.0, alpha: 0.5)
    }
    @nonobjc class var glfDarkSlateBlue: UIColor {
        return UIColor(red: 22.0 / 255.0, green: 66.0 / 255.0, blue: 91.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfBlushPink: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 140.0 / 255.0, blue: 143.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfGreenBlueTwo: UIColor {
        return UIColor(red: 0.0, green: 193.0 / 255.0, blue: 140.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfYellow: UIColor {
        return UIColor(red: 247.0 / 255.0, green: 212.0 / 255.0, blue: 5.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfRed: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 55.0 / 255.0, blue: 55.0 / 255.0, alpha: 1.0)
    }
    @nonobjc class var glfGreenish: UIColor {
        return UIColor(red: 19.0 / 255.0, green: 195.0 / 255.0, blue: 140.0 / 255.0, alpha: 1.0)
    }

}

// Text styles
import UIKit
extension UIFont {
    
    @nonobjc class var glfTextStyle6: UIFont {
        return UIFont.systemFont(ofSize: 10.0, weight: .medium)
    }
    
    @nonobjc class var glfTextStyle: UIFont {
        return UIFont.systemFont(ofSize: 7.0, weight: .semibold)
    }
    
    @nonobjc class var glfTextStyle2: UIFont {
        return UIFont.systemFont(ofSize: 7.0, weight: .medium)
    }
    
    @nonobjc class var glfTextStyle4: UIFont {
        return UIFont.systemFont(ofSize: 6.5, weight: .medium)
    }
    
    @nonobjc class var glfTextStyle3: UIFont {
        return UIFont.systemFont(ofSize: 6.5, weight: .regular)
    }
    
    @nonobjc class var glfTextStyle5: UIFont {
        return UIFont.systemFont(ofSize: 4.0, weight: .medium)
    }
}
extension UIColor {
    
    convenience init(red: Int, green: Int, blue: Int) {
        assert(red >= 0 && red <= 255, "Invalid red component")
        assert(green >= 0 && green <= 255, "Invalid green component")
        assert(blue >= 0 && blue <= 255, "Invalid blue component")
        
        self.init(red: CGFloat(red) / 255.0, green: CGFloat(green) / 255.0, blue: CGFloat(blue) / 255.0, alpha: 1.0)
    }
    
    convenience init(rgb: Int) {
        self.init(
            red: (rgb >> 16) & 0xFF,
            green: (rgb >> 8) & 0xFF,
            blue: rgb & 0xFF
        )
    }
}

